### PR TITLE
Set up automated testing and test Copy Files task

### PR DESCRIPTION
**Pull request by svetogam**
This is an example test for #10.

It runs the Execution scene on a project that has previously been set up in Project Builder. The test projects are kept in a folder with a `.gdignore` file so they don't mess up opening Project Builder in Godot.

This general testing template can be used for testing many but not all tasks. It can test operations on the filesystem, it can test weird uses of subroutines, and maybe it can also test exporting a project.

I used [GUT](https://github.com/bitwes/Gut) which is the most popular testing framework for Godot projects. The GUT config is a little weird because it includes the necessary configuration to search for tests together with personal customizations. I think you have to load the file manually the first time because it keeps the real configuration in your user data folder.

Though it's only intended as an example, it could also be merged as-is. I can write more tests like this if you give confirmation that you would use them and maintain them. Otherwise this can serve as an example of what kind of tests could be made in the future.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I looked at the test and it looks fine. I think the implementation is ok as is, though the `.gitattributes` has to be modified to exclude tests.

> The test projects are kept in a folder with a .gdignore file so they don't mess up opening Project Builder in Godot.

Nested projects are automatically ignored, so you don't need .gdignore.

___

As for the testing in general, I think it's more important in actively developed project where there is high risk of regressions. Project Builder isn't really like that, however there is still value in coming up with tests to make sure everything works correctly. Whether they need to be automated is another thing; if you find a bug and fix it, the test is mostly redundant.

I'm not very interested in adding tests myself, because I don't really have time for that. If you want to add more tests yourself, I can give brief reviews and merge them, but I can't guarantee maintenance (other than ensuring that tests are passing I guess).

I can merge this one if you modify `.gitattributes` as I mentioned; it's important for AssetLib.

**Comment by svetogam** [comment]
I didn't know that nested projects are ignored automatically, but I kept the .gdignore file around because it silences a warning. I also excluded stuff in the export template.

---

I think you're undervaluing automated testing a little. From my perspective, I would like to be able to rely on this utility for my own project and I would like to minimize the time I spend testing manually. Automated tests are good for both.

While there's less chance of regressions in a small project like this, regressions that do happen will be worse because there's no possibility of undoing much of what Project Builder does. I'd say this makes automated tests as valuable for Project Builder as for a large project.

Second, I think making tests even this early saves time in the long run. Having tests around would have already saved requiring some extra manual testing and discussion on the cyclical subroutine bug. For saving time, it comes down to having tests that are not much more time-consuming to make than testing manually. So I can only recommend making tests that follow an easily reusable template, like I tried to do here.

In general, I think making tests becomes a net gain for saving time when there starts to be any substantial refactoring work being done. The time to make automated tests is before refactoring, but I think that time will come eventually and it will be better to have tests around sooner rather than later, so I think now is the best time for adding them.

**Comment by KoBeWi** [comment]
I don't plan any refactoring right now, but yeah, if it happens the tests will be useful.

**Comment by KoBeWi** [comment]
Thanks!

**Pull request merged**
